# Generated by Django 3.2.12 on 2022-05-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_connection_author_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='conversation_initialised',
            field=models.BooleanField(default=False),
        ),
    ]
