# Generated by Django 3.2.12 on 2022-05-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_connection_conversation_initialised'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionmessage',
            name='is_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
