# Generated by Django 3.2.12 on 2022-05-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_survey_surveyoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
