# Generated by Django 3.2.12 on 2022-05-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_surveyoption_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted',
        ),
    ]
